# Generated by Django 2.1.4 on 2018-12-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='tracks',
            field=models.ManyToManyField(to='compositions.Track'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_file',
            field=models.FileField(upload_to='tracks'),
        ),
    ]
