# Generated by Django 2.1.4 on 2018-12-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='track',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='track',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Composition',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
