# Generated by Django 2.1.4 on 2019-06-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0002_auto_20190612_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
