# Generated by Django 2.1.4 on 2019-06-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0003_auto_20190613_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackinvariation',
            name='track',
        ),
        migrations.DeleteModel(
            name='TrackInVariation',
        ),
        migrations.CreateModel(
            name='TrackInVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.ForeignKey(on_delete=models.CASCADE, to='compositions.Track')),
                ('start_timing', models.FloatField(default=0)),
                ('stop_timing', models.FloatField(default=0)),
            ],
        ),

    ]
