# Generated by Django 2.1.4 on 2019-06-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0004_auto_20190613_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='likes',
        ),
    ]
