from .CreateCompositionView import *
from .IndexView import *
from .ProfileView import *
from .CreateVariationView import *
from .CreateTrackView import *
from .ShowCompositionView import *
from .ShowVariationView import *
from .DeleteCompositionView import *
from .DeleteTrackView import *
from .ForkVariationView import *
from .EditVariationView import *
from .RatingsView import *
from .LikeButtonView import *
from .SearchCompositionsView import *
