from .IndexTest import *
from .CreateModelsTest import *
from .LoginRequiredTest import *
from .ReverseWithParams import *
from .DeleteModelsTest import *
from .CompositionTest import *
from .ForkVariationTest import *
from .ShowVariationTest import *
from .ProfileTest import *
from .EditVariationTest import *
